<<<<<<< HEAD
<<<<<<<< HEAD:apps/web/app/layout.tsx
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
========
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
>>>>>>>> 0533fb247c17589228809e0b339c93d2b9da96f1:apps/web/src/app/layout.tsx

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<<< HEAD:apps/web/app/layout.tsx
  title: 'Tech Innovation Summit 2024',
  description: 'Join industry leaders and innovators for a day of inspiration, learning, and networking',
========
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>>> 0533fb247c17589228809e0b339c93d2b9da96f1:apps/web/src/app/layout.tsx
=======
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Tech Innovation Summit 2024',
  description: 'Join industry leaders and innovators for a day of inspiration, learning, and networking',
>>>>>>> 0533fb247c17589228809e0b339c93d2b9da96f1
};

export default function RootLayout({
  children,
<<<<<<< HEAD
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<<< HEAD:apps/web/app/layout.tsx
      <body className={inter.className}>{children}</body>
========
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
>>>>>>>> 0533fb247c17589228809e0b339c93d2b9da96f1:apps/web/src/app/layout.tsx
    </html>
  );
}
=======
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
>>>>>>> 0533fb247c17589228809e0b339c93d2b9da96f1
